export const GET_ALL_PRODUCTS_LOADING = "GET_ALL_PRODUCTS_LOADING"
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS"
export const GET_ALL_PRODUCTS_FAILURE = "GET_ALL_PRODUCTS_FAILURE"

export const REGISTER_API_LOADING = "REGISTER_API_LOADING"
export const REGISTER_API_SUCCESS = "REGISTER_API_SUCCESS"
export const REGISTER_API_FAILURE = "REGISTER_API_FAILURE"

export const LOGIN_API_LOADING = "LOGIN_API_LOADING"
export const LOGIN_API_SUCCESS = "LOGIN_API_SUCCESS"
export const LOGIN_API_FAILURE = "LOGIN_API_FAILURE"

export const CLEAN_AUTH = "CLEAN_AUTH"
export const CLEAN_CART = "CLEAN_CART"
export const LOGOUT = "LOGOUT"

export const ADD_TO_CART_LOADING = "ADD_TO_CART_LOADING"
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE"

export const GET_CART_LOADING = "GET_CART_LOADING"
export const GET_CART_SUCCESS = "GET_CART_SUCCESS"
export const GET_CART_FAILURE = "GET_CART_FAILURE"